server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/auth/**

        - id: business-service
          predicates:
            - Path=/business/**

        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/client/**