export const CLIENTS = [
  {
    user_id: 1,
    first_name: 'Anna',
    last_name: 'Kowalska',
    email: 'anna.kowalska@example.com',
    phone: '+48 123 456 789',
    birth_date: '1985-05-12',
    gender: 'female',
    address: 'ul. Kwiatowa 15',
    city: 'Warszawa',
    postal_code: '00-123',
    registration_date: '2023-01-15',
    last_login: '2025-04-10',
    account_status: 'active',
    marketing_consent: true,
    loyalty_points_balance: 230,
    notes: 'Wrażliwa skóra, preferuje naturalne produkty',
  },
  {
    user_id: 2,
    first_name: 'Marek',
    last_name: 'Nowak',
    email: 'marek.nowak@example.com',
    phone: '+48 987 654 321',
    birth_date: '1990-09-23',
    gender: 'male',
    address: 'ul. Słoneczna 7/4',
    city: 'Kraków',
    postal_code: '30-001',
    registration_date: '2023-05-20',
    last_login: '2025-04-14',
    account_status: 'active',
    marketing_consent: false,
    loyalty_points_balance: 75,
    notes: 'Często się spóźnia na wizyty',
  },
  {
    user_id: 3,
    first_name: 'Karolina',
    last_name: 'Wiśniewska',
    email: 'karolina.wisniewska@example.com',
    phone: '+48 555 123 456',
    birth_date: '1992-12-03',
    gender: 'female',
    address: 'ul. Lipowa 22',
    city: 'Wrocław',
    postal_code: '50-125',
    registration_date: '2023-11-05',
    last_login: '2025-03-30',
    account_status: 'active',
    marketing_consent: true,
    loyalty_points_balance: 450,
    notes: 'VIP - zawsze prosi o Agnieszkę jako kosmetyczkę',
  },
  {
    user_id: 4,
    first_name: 'Piotr',
    last_name: 'Lewandowski',
    email: 'piotr.lewandowski@example.com',
    phone: '+48 602 305 407',
    birth_date: '1980-07-15',
    gender: 'male',
    address: 'ul. Polna 5',
    city: 'Gdańsk',
    postal_code: '80-008',
    registration_date: '2024-02-10',
    last_login: '2025-04-01',
    account_status: 'active',
    marketing_consent: true,
    loyalty_points_balance: 25,
    notes: 'Regularnie kupuje kosmetyki po zabiegach',
  },
  {
    user_id: 5,
    first_name: 'Magdalena',
    last_name: 'Dąbrowska',
    email: 'magdalena.dabrowska@example.com',
    phone: '+48 789 456 123',
    birth_date: '1995-03-27',
    gender: 'female',
    address: 'ul. Mickiewicza 18/7',
    city: 'Poznań',
    postal_code: '60-222',
    registration_date: '2024-07-22',
    last_login: '2025-04-12',
    account_status: 'inactive',
    marketing_consent: false,
    loyalty_points_balance: 120,
    notes: 'Alergiczna na lateks - stosować hipoalergiczne rękawiczki',
  },
];

export const EMPLOYERS = [
  {
    employee_id: 1,
    user_id: 101,
    first_name: 'Agnieszka',
    last_name: 'Zielińska',
    email: 'a.zielinska@beautyspot.pl',
    phone: '+48 600 100 200',
    position: 'Kosmetolog',
    bio: 'Specjalistka z 8-letnim doświadczeniem w zabiegach anti-aging',
    hire_date: '2020-03-15',
    status: 'active',
    location_id: 1,
    specialization: 'Zabiegi anti-aging, mezoterapia',
    image_url: '/images/staff/agnieszka_z.jpg',
    max_appointments_per_day: 10,
    hourly_rate: 80.0,
  },
  {
    employee_id: 2,
    user_id: 102,
    first_name: 'Katarzyna',
    last_name: 'Adamczyk',
    email: 'k.adamczyk@beautyspot.pl',
    phone: '+48 600 200 300',
    position: 'Stylistka paznokci',
    bio: 'Mistrzyni stylizacji paznokci, specjalistka w zdobnictwie artystycznym',
    hire_date: '2021-05-10',
    status: 'active',
    location_id: 1,
    specialization: 'Manicure hybrydowy, zdobienia artystyczne',
    image_url: '/images/staff/katarzyna_a.jpg',
    max_appointments_per_day: 12,
    hourly_rate: 60.0,
  },
  {
    employee_id: 3,
    user_id: 103,
    first_name: 'Michał',
    last_name: 'Krawczyk',
    email: 'm.krawczyk@beautyspot.pl',
    phone: '+48 601 300 400',
    position: 'Masażysta',
    bio: 'Certyfikowany terapeuta z doświadczeniem w masażach leczniczych i relaksacyjnych',
    hire_date: '2022-01-20',
    status: 'on_leave',
    location_id: 2,
    specialization: 'Masaż klasyczny, masaż tkanek głębokich',
    image_url: '/images/staff/michal_k.jpg',
    max_appointments_per_day: 8,
    hourly_rate: 90.0,
  },
  {
    employee_id: 4,
    user_id: 104,
    first_name: 'Joanna',
    last_name: 'Witkowska',
    email: 'j.witkowska@beautyspot.pl',
    phone: '+48 602 400 500',
    position: 'Kosmetolog',
    bio: 'Ekspertka w zakresie pielęgnacji cery problematycznej i trądzikowej',
    hire_date: '2023-03-05',
    status: 'active',
    location_id: 1,
    specialization: 'Terapie cery problematycznej, peelingi chemiczne',
    image_url: '/images/staff/joanna_w.jpg',
    max_appointments_per_day: 9,
    hourly_rate: 75.0,
  },
  {
    employee_id: 5,
    user_id: 105,
    first_name: 'Tomasz',
    last_name: 'Jankowski',
    email: 't.jankowski@beautyspot.pl',
    phone: '+48 603 500 600',
    position: 'Manager salonu',
    bio: 'Z wykształcenia kosmetolog, obecnie zarządza zespołem i dba o standardy obsługi',
    hire_date: '2019-11-12',
    status: 'active',
    location_id: 2,
    specialization: 'Konsultacje, zarządzanie',
    image_url: '/images/staff/tomasz_j.jpg',
    max_appointments_per_day: 5,
    hourly_rate: 100.0,
  },
];

export const SERVICES = [
  {
    service_id: 1,
    name: 'Manicure hybrydowy',
    description:
      'Trwały manicure z użyciem lakieru hybrydowego, utwardzanego lampą UV/LED. Efekt utrzymuje się do 3 tygodni.',
    category_id: 1,
    duration: 60,
    price: 120.0,
    active: true,
    image_url: '/images/services/hybrid_manicure.jpg',
    preparation_time: 0,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [
      { product_id: 12, quantity: 1, unit: 'ml' },
      { product_id: 15, quantity: 5, unit: 'ml' },
    ],
  },
  {
    service_id: 2,
    name: 'Pedicure SPA',
    description:
      'Kompleksowy pedicure z peelingiem, maseczką i masażem stóp. Zawiera malowanie paznokci lakierem klasycznym.',
    category_id: 1,
    duration: 75,
    price: 160.0,
    active: true,
    image_url: '/images/services/spa_pedicure.jpg',
    preparation_time: 5,
    cleanup_time: 10,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 23, quantity: 15, unit: 'ml' },
      { product_id: 27, quantity: 10, unit: 'ml' },
      { product_id: 31, quantity: 5, unit: 'ml' },
    ],
  },
  {
    service_id: 3,
    name: 'Masaż relaksacyjny pleców',
    description:
      'Masaż klasyczny całych pleców z elementami masażu limfatycznego. Poprawia ukrwienie i rozluźnia napięte mięśnie.',
    category_id: 2,
    duration: 30,
    price: 130.0,
    active: true,
    image_url: '/images/services/back_massage.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [{ product_id: 45, quantity: 20, unit: 'ml' }],
  },
  {
    service_id: 4,
    name: 'Masaż całego ciała',
    description:
      'Holistyczny masaż całego ciała z użyciem aromatycznych olejków. Głęboko relaksuje i odpręża.',
    category_id: 2,
    duration: 60,
    price: 220.0,
    active: true,
    image_url: '/images/services/full_body_massage.jpg',
    preparation_time: 5,
    cleanup_time: 10,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [{ product_id: 46, quantity: 50, unit: 'ml' }],
  },
  {
    service_id: 5,
    name: 'Podstawowe oczyszczanie twarzy',
    description:
      'Zabieg oczyszczający skórę twarzy, obejmujący demakijaż, peeling, oczyszczanie manualne i maskę.',
    category_id: 3,
    duration: 60,
    price: 180.0,
    active: true,
    image_url: '/images/services/facial_cleansing.jpg',
    preparation_time: 5,
    cleanup_time: 10,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 52, quantity: 5, unit: 'ml' },
      { product_id: 53, quantity: 10, unit: 'ml' },
      { product_id: 57, quantity: 20, unit: 'ml' },
    ],
  },
  {
    service_id: 6,
    name: 'Zabieg anti-aging z kwasem hialuronowym',
    description:
      'Intensywny zabieg przeciwstarzeniowy z użyciem kwasu hialuronowego i peptydów. Redukuje drobne zmarszczki i poprawia jędrność skóry.',
    category_id: 3,
    duration: 90,
    price: 350.0,
    active: true,
    image_url: '/images/services/antiaging_treatment.jpg',
    preparation_time: 10,
    cleanup_time: 10,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [
      { product_id: 61, quantity: 3, unit: 'ml' },
      { product_id: 64, quantity: 5, unit: 'ml' },
      { product_id: 67, quantity: 15, unit: 'ml' },
    ],
  },
  {
    service_id: 7,
    name: 'Depilacja woskiem - nogi całe',
    description: 'Depilacja woskiem ciepłym całych nóg. Efekt utrzymuje się do 4 tygodni.',
    category_id: 4,
    duration: 45,
    price: 140.0,
    active: true,
    image_url: '/images/services/legs_waxing.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 72, quantity: 40, unit: 'g' },
      { product_id: 73, quantity: 10, unit: 'ml' },
    ],
  },
  {
    service_id: 8,
    name: 'Depilacja woskiem - pachy',
    description:
      'Szybka i skuteczna depilacja woskiem okolic pach. Efekt utrzymuje się do 4 tygodni.',
    category_id: 4,
    duration: 15,
    price: 60.0,
    active: true,
    image_url: '/images/services/armpit_waxing.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 72, quantity: 10, unit: 'g' },
      { product_id: 73, quantity: 5, unit: 'ml' },
    ],
  },
  {
    service_id: 9,
    name: 'Przedłużanie rzęs metodą 1:1',
    description:
      'Profesjonalne przedłużanie rzęs metodą 1:1. Efekt naturalnych, gęstych rzęs utrzymuje się do 4 tygodni.',
    category_id: 5,
    duration: 120,
    price: 250.0,
    active: true,
    image_url: '/images/services/eyelash_extension.jpg',
    preparation_time: 10,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [{ product_id: 82, quantity: 1, unit: 'zestaw' }],
  },
  {
    service_id: 10,
    name: 'Makijaż dzienny',
    description:
      'Lekki makijaż dzienny podkreślający naturalne piękno. Idealny na co dzień lub specjalne okazje w ciągu dnia.',
    category_id: 5,
    duration: 45,
    price: 150.0,
    active: true,
    image_url: '/images/services/day_makeup.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [{ product_id: 91, quantity: 1, unit: 'zestaw' }],
  },
  {
    service_id: 11,
    name: 'Pakiet ślubny - makijaż i fryzura próbna',
    description:
      'Konsultacja ślubna wraz z próbnym makijażem i upięciem włosów. Zawiera planowanie stylizacji na dzień ślubu.',
    category_id: 6,
    duration: 180,
    price: 450.0,
    active: true,
    image_url: '/images/services/bridal_package_trial.jpg',
    preparation_time: 15,
    cleanup_time: 15,
    available_for_online_booking: false,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 91, quantity: 1, unit: 'zestaw' },
      { product_id: 101, quantity: 1, unit: 'zestaw' },
    ],
  },
  {
    service_id: 12,
    name: 'Pakiet Day SPA',
    description:
      'Kompletny pakiet zabiegów pielęgnacyjnych, obejmujący masaż całego ciała, zabieg na twarz, manicure i pedicure. Lunch w cenie.',
    category_id: 6,
    duration: 240,
    price: 650.0,
    active: true,
    image_url: '/images/services/day_spa_package.jpg',
    preparation_time: 15,
    cleanup_time: 15,
    available_for_online_booking: false,
    popular: true,
    tax_rate: 23,
    products_used: [
      { product_id: 45, quantity: 50, unit: 'ml' },
      { product_id: 57, quantity: 20, unit: 'ml' },
      { product_id: 15, quantity: 5, unit: 'ml' },
      { product_id: 27, quantity: 10, unit: 'ml' },
    ],
  },
  {
    service_id: 13,
    name: 'Konsultacja kosmetologiczna',
    description:
      'Profesjonalna konsultacja z kosmetologiem. Analiza skóry, omówienie problemów i opracowanie planu pielęgnacji.',
    category_id: 7,
    duration: 30,
    price: 80.0,
    active: true,
    image_url: '/images/services/cosmetic_consultation.jpg',
    preparation_time: 0,
    cleanup_time: 0,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [],
  },
  {
    service_id: 14,
    name: 'Stylizacja brwi henną',
    description:
      'Kompleksowa stylizacja brwi obejmująca regulację, koloryzację henną i modelowanie. Efekt utrzymuje się do 4 tygodni.',
    category_id: 5,
    duration: 30,
    price: 90.0,
    active: true,
    image_url: '/images/services/eyebrow_styling.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: true,
    tax_rate: 23,
    products_used: [
      { product_id: 111, quantity: 1, unit: 'aplikacja' },
      { product_id: 112, quantity: 2, unit: 'ml' },
    ],
  },
  {
    service_id: 15,
    name: 'Peeling kawitacyjny',
    description:
      'Bezbolesny zabieg oczyszczający skórę z wykorzystaniem ultradźwięków. Idealny dla skóry wrażliwej.',
    category_id: 3,
    duration: 30,
    price: 120.0,
    active: true,
    image_url: '/images/services/cavitation_peeling.jpg',
    preparation_time: 5,
    cleanup_time: 5,
    available_for_online_booking: true,
    popular: false,
    tax_rate: 23,
    products_used: [
      { product_id: 52, quantity: 5, unit: 'ml' },
      { product_id: 121, quantity: 10, unit: 'ml' },
    ],
  },
];
